######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 23 22:17:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editor.h editor_gl.h main.h polygon.h vertex.h
SOURCES += editor.cpp editor_gl.cpp main.cpp polygon.cpp vertex.cpp
QT += opengl
